[build]
  builder = "nix"
  buildCommand = "npm install && npm run build"

[deploy]
  startCommand = "cd server && npm install && node index.js"
  healthcheckPath = "/"
  healthcheckTimeout = 300

[env]
  NODE_ENV = "production"
  PORT = "3001"
