services:
  - type: web
    name: ilnaz-launcher
    env: node
    plan: starter
    rootDir: .
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
